# Generated by Django 2.1.3 on 2018-11-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('momofit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(default=20, help_text='Enter age'),
        ),
    ]
