# Generated by Django 2.1.3 on 2018-11-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('momofit', '0002_customuser_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='height',
            field=models.IntegerField(default=160),
        ),
        migrations.AddField(
            model_name='customuser',
            name='kcal',
            field=models.IntegerField(default=1500),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sex',
            field=models.CharField(default='Male', max_length=5),
        ),
        migrations.AddField(
            model_name='customuser',
            name='weight',
            field=models.IntegerField(default=60),
        ),
    ]
