# Generated by Django 2.1.3 on 2018-11-25 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('momofit', '0007_auto_20181125_1720'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gymlist',
            table='gym_list',
        ),
    ]
