# Generated by Django 2.1.3 on 2018-11-25 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('momofit', '0008_auto_20181125_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='fooditem',
            table='food_item',
        ),
        migrations.AlterModelTable(
            name='foodrecord',
            table='food_record',
        ),
        migrations.AlterModelTable(
            name='gymrecord',
            table='gym_record',
        ),
        migrations.AlterModelTable(
            name='history',
            table='history',
        ),
        migrations.AlterModelTable(
            name='itemlist',
            table='item_list',
        ),
        migrations.AlterModelTable(
            name='menu',
            table='menu',
        ),
        migrations.AlterModelTable(
            name='store',
            table='store',
        ),
        migrations.AlterModelTable(
            name='trainrecord',
            table='train_record',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
