# Generated by Django 2.1.3 on 2018-11-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('momofit', '0009_auto_20181125_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='fat',
            field=models.FloatField(null=True, verbose_name='體脂率(%)'),
        ),
    ]
