# Generated by Django 2.1.3 on 2018-11-30 11:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('momofit', '0010_history_fat'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_pic',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
