# Generated by Django 2.1.3 on 2018-11-30 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('momofit', '0011_user_user_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='display',
            field=models.BooleanField(default=False),
        ),
    ]
