# Generated by Django 2.1.3 on 2018-12-01 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('momofit', '0012_menu_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
