# Generated by Django 2.1.3 on 2018-12-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('momofit', '0013_history_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='id',
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_id',
            field=models.IntegerField(db_column='menu_id', default=False, primary_key=True, serialize=False),
        ),
    ]
