# Generated by Django 2.1.3 on 2018-12-02 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('momofit', '0014_auto_20181202_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='items',
        ),
        migrations.AddField(
            model_name='menu',
            name='items',
            field=models.ForeignKey(db_column='item_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='momofit.ItemList'),
        ),
    ]
