# Generated by Django 2.1.3 on 2018-12-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('momofit', '0015_auto_20181202_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_id',
            field=models.AutoField(db_column='menu_id', primary_key=True, serialize=False),
        ),
    ]
