# Generated by Django 2.1.3 on 2018-12-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('momofit', '0018_auto_20181202_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodrecord',
            name='fr_date',
            field=models.DateField(db_column='fr_date', default=False),
        ),
        migrations.AlterField(
            model_name='trainrecord',
            name='train_date',
            field=models.DateField(db_column='train_date'),
        ),
    ]
