# Generated by Django 2.1.3 on 2018-12-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('momofit', '0019_auto_20181206_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_rep',
            field=models.IntegerField(),
        ),
    ]
