# Generated by Django 2.1.3 on 2018-12-08 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('momofit', '0021_remove_gymrecord_gr_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainrecord',
            name='gr_id',
        ),
        migrations.AddField(
            model_name='trainrecord',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
