# Generated by Django 2.1.3 on 2018-12-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('momofit', '0022_auto_20181208_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainrecord',
            name='gym_name',
            field=models.CharField(db_column='gym_name', default='政大體育館', max_length=30),
            preserve_default=False,
        ),
    ]
