# Generated by Django 2.1.3 on 2018-12-08 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('momofit', '0023_trainrecord_gym_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='itemlist',
            table='item',
        ),
    ]
