# Generated by Django 2.1.3 on 2018-12-08 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('momofit', '0025_auto_20181208_2340'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='trainrecord',
            table='train_record',
        ),
    ]
