# Generated by Django 2.1.3 on 2018-12-08 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('momofit', '0026_auto_20181208_2344'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='foodrecord',
            table='food',
        ),
    ]
