# Generated by Django 2.1.3 on 2018-12-08 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('momofit', '0027_auto_20181208_2345'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fooditem',
            table='food_detail',
        ),
    ]
