# Generated by Django 2.1.3 on 2018-12-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('momofit', '0028_auto_20181208_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='food',
            field=models.CharField(db_column='food_name', max_length=50),
        ),
    ]
