# Generated by Django 2.1.3 on 2018-12-08 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('momofit', '0029_auto_20181208_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodrecord',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
