# Generated by Django 2.1.3 on 2018-12-08 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('momofit', '0030_auto_20181208_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='food_id',
            field=models.AutoField(db_column='food_detail_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='foodrecord',
            name='food_id',
            field=models.ForeignKey(db_column='food_detail_id', on_delete=django.db.models.deletion.DO_NOTHING, to='momofit.FoodItem'),
        ),
    ]
