# Generated by Django 2.1.3 on 2018-12-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('momofit', '0031_auto_20181209_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodrecord',
            name='fr_id',
            field=models.AutoField(db_column='food_id', primary_key=True, serialize=False),
        ),
    ]
