# Generated by Django 2.1.3 on 2018-12-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('momofit', '0032_auto_20181209_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymrecord',
            name='gym_id',
        ),
        migrations.RemoveField(
            model_name='gymrecord',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='trainrecord',
            name='train_set',
            field=models.IntegerField(db_column='set'),
        ),
        migrations.DeleteModel(
            name='GymList',
        ),
        migrations.DeleteModel(
            name='GymRecord',
        ),
    ]
