# Generated by Django 2.1.3 on 2018-12-09 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('momofit', '0035_auto_20181209_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainrecord',
            name='weight',
            field=models.IntegerField(db_column='weight'),
        ),
    ]
