# Generated by Django 2.1.3 on 2018-12-09 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('momofit', '0036_auto_20181209_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlist',
            name='item_type',
            field=models.CharField(db_column='item_type', max_length=2),
        ),
    ]
